# Generated by Django 2.2.3 on 2019-12-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('tags', models.CharField(max_length=20)),
                ('categories', models.CharField(max_length=20)),
                ('thumbnail', models.FileField(upload_to='media/thumbnails')),
                ('videos', models.FileField(upload_to='media/videos')),
            ],
        ),
    ]
