# Generated by Django 2.2.3 on 2019-12-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid',
            name='thumbnail',
            field=models.FileField(upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='vid',
            name='videos',
            field=models.FileField(upload_to='videos'),
        ),
    ]
