# Generated by Django 2.2.3 on 2019-12-27 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20191225_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='vid',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
